// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicesDeskUCABWS.Data;

#nullable disable

namespace ServicesDeskUCABWS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Bitacora_Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TicketId");

                    b.ToTable("Bitacora_Tickets");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Cargo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Departamentoid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_eliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_ultima_edicion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_departamental")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("Departamentoid");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Departamento", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_eliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_ultima_edicion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("id_grupo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.HasIndex("id_grupo");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.DepartamentoTipo_Ticket", b =>
                {
                    b.Property<Guid>("Tipo_Ticekt_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tipo_TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Tipo_Ticekt_Id", "DepartamentoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("tipo_TicketId");

                    b.ToTable("DepartamentoTipo_Ticket");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Departamentoid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Estado_PadreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_eliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_ultima_edic")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Departamentoid");

                    b.HasIndex("Estado_PadreId");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Etiquetas");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.EtiquetaTipoEstado", b =>
                {
                    b.Property<Guid>("etiquetaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("tipoEstadoID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("etiquetaID", "tipoEstadoID");

                    b.HasIndex("tipoEstadoID");

                    b.ToTable("EtiquetasTipoEstados");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Familia_Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Familia_Tickets");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Flujo_Aprobacion", b =>
                {
                    b.Property<Guid>("IdTicket")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCargo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Cargoid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Maximo_Rechazado_nivel")
                        .HasColumnType("int");

                    b.Property<int?>("Minimo_aprobado_nivel")
                        .HasColumnType("int");

                    b.Property<int?>("OrdenAprobacion")
                        .HasColumnType("int");

                    b.Property<Guid?>("Tipo_TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdTicket", "IdCargo");

                    b.HasIndex("Cargoid");

                    b.HasIndex("Tipo_TicketId");

                    b.ToTable("Flujos_Aprobaciones");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Grupo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_eliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_ultima_edicion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Modelo_Aprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("discrimanador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modelos_Aprobacion");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.PlantillaNotificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TipoEstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipoEstadoId")
                        .IsUnique()
                        .HasFilter("[TipoEstadoId] IS NOT NULL");

                    b.ToTable("PlantillasNotificaciones");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Prioridad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_descripcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_ultima_edic")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Prioridades");

                    b.HasCheckConstraint("prioridad_estado_chk", "estado = 'Habilitado' or estado = 'Deshabilitado'");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c8a156b-7383-4610-8539-30ccf7298162"),
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("8c8a156b-7383-4610-8539-30ccf7298163"),
                            Name = "Empleado"
                        },
                        new
                        {
                            Id = new Guid("8c8a156b-7383-4610-8539-30ccf7298161"),
                            Name = "Cliente"
                        });
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.RolUsuario", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("RolUsuarios");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8c8a156b-7383-4610-8539-30ccf7298164"),
                            RolId = new Guid("8c8a156b-7383-4610-8539-30ccf7298162")
                        });
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Departamento_Destinoid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Familia_TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrioridadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Ticket_PadreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Tipo_TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_eliminacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nro_cargo_actual")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Departamento_Destinoid");

                    b.HasIndex("EmisorId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("Familia_TicketId");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("Ticket_PadreId");

                    b.HasIndex("Tipo_TicketId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Tipo_Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("fecha_eliminacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("permiso")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Tipos_Estados");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Tipo_Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Maximo_Rechazado")
                        .HasColumnType("int");

                    b.Property<int?>("Minimo_Aprobado")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_elim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_ult_edic")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Tipos_Tickets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Tipo_Ticket");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_eliminacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("fecha_nacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_ultima_edicion")
                        .HasColumnType("datetime2");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primer_apellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("primer_nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("segundo_apellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("segundo_nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("correo")
                        .IsUnique()
                        .HasFilter("[correo] IS NOT NULL");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Votos_Ticket", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTicket")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Turno")
                        .HasColumnType("int");

                    b.Property<string>("comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("voto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario", "IdTicket");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TicketId");

                    b.ToTable("Votos_Tickets");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Administrador", b =>
                {
                    b.HasBaseType("ServicesDeskUCABWS.Entities.Usuario");

                    b.Property<int>("NumeroDeCuentasBloqueadas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("1");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c8a156b-7383-4610-8539-30ccf7298164"),
                            cedula = 0,
                            correo = "admin@gmail.com",
                            fecha_creacion = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            fecha_eliminacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fecha_ultima_edicion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            gender = " ",
                            password = "admin",
                            primer_apellido = "",
                            primer_nombre = "",
                            segundo_apellido = "",
                            segundo_nombre = "",
                            NumeroDeCuentasBloqueadas = 0
                        });
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Cliente", b =>
                {
                    b.HasBaseType("ServicesDeskUCABWS.Entities.Usuario");

                    b.HasDiscriminator().HasValue("3");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Empleado", b =>
                {
                    b.HasBaseType("ServicesDeskUCABWS.Entities.Usuario");

                    b.Property<Guid?>("Cargoid")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("Cargoid");

                    b.HasDiscriminator().HasValue("2");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.TipoTicket_FlujoAprobacionJerarquico", b =>
                {
                    b.HasBaseType("ServicesDeskUCABWS.Entities.Tipo_Ticket");

                    b.HasDiscriminator().HasValue("Modelo_Jerarquico");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.TipoTicket_FlujoAprobacionParalelo", b =>
                {
                    b.HasBaseType("ServicesDeskUCABWS.Entities.Tipo_Ticket");

                    b.HasDiscriminator().HasValue("Modelo_Paralelo");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.TipoTicket_FlujoNoAprobacion", b =>
                {
                    b.HasBaseType("ServicesDeskUCABWS.Entities.Tipo_Ticket");

                    b.HasDiscriminator().HasValue("Modelo_No_Aprobacion");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Bitacora_Ticket", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Estado", "Estado")
                        .WithMany("Bitacora_Tickets")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicesDeskUCABWS.Entities.Ticket", "Ticket")
                        .WithMany("Bitacora_Tickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Cargo", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("Departamentoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Departamento", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Grupo", "grupo")
                        .WithMany("departamentos")
                        .HasForeignKey("id_grupo");

                    b.Navigation("grupo");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.DepartamentoTipo_Ticket", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Departamento", "departamento")
                        .WithMany("Tipo_Tickets")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicesDeskUCABWS.Entities.Tipo_Ticket", "tipo_Ticket")
                        .WithMany("Departamentos")
                        .HasForeignKey("tipo_TicketId");

                    b.Navigation("departamento");

                    b.Navigation("tipo_Ticket");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Estado", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("Departamentoid");

                    b.HasOne("ServicesDeskUCABWS.Entities.Tipo_Estado", "Estado_Padre")
                        .WithMany()
                        .HasForeignKey("Estado_PadreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Estado_Padre");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.EtiquetaTipoEstado", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Etiqueta", "etiqueta")
                        .WithMany("etiquetaTipoEstado")
                        .HasForeignKey("etiquetaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicesDeskUCABWS.Entities.Tipo_Estado", "tipoEstado")
                        .WithMany("etiquetaTipoEstado")
                        .HasForeignKey("tipoEstadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("etiqueta");

                    b.Navigation("tipoEstado");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Flujo_Aprobacion", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Cargo", "Cargo")
                        .WithMany("Flujo_Aprobacion")
                        .HasForeignKey("Cargoid");

                    b.HasOne("ServicesDeskUCABWS.Entities.Tipo_Ticket", "Tipo_Ticket")
                        .WithMany("Flujo_Aprobacion")
                        .HasForeignKey("Tipo_TicketId");

                    b.Navigation("Cargo");

                    b.Navigation("Tipo_Ticket");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.PlantillaNotificacion", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Tipo_Estado", "TipoEstado")
                        .WithMany()
                        .HasForeignKey("TipoEstadoId");

                    b.Navigation("TipoEstado");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.RolUsuario", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicesDeskUCABWS.Entities.Usuario", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Ticket", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Departamento", "Departamento_Destino")
                        .WithMany()
                        .HasForeignKey("Departamento_Destinoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicesDeskUCABWS.Entities.Empleado", "Emisor")
                        .WithMany("Lista_Ticket")
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ServicesDeskUCABWS.Entities.Estado", "Estado")
                        .WithMany("ListaTickets")
                        .HasForeignKey("EstadoId");

                    b.HasOne("ServicesDeskUCABWS.Entities.Familia_Ticket", "Familia_Ticket")
                        .WithMany("Lista_Ticket")
                        .HasForeignKey("Familia_TicketId");

                    b.HasOne("ServicesDeskUCABWS.Entities.Prioridad", "Prioridad")
                        .WithMany()
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServicesDeskUCABWS.Entities.Empleado", "Responsable")
                        .WithMany("Tickets_Propios")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServicesDeskUCABWS.Entities.Ticket", "Ticket_Padre")
                        .WithMany()
                        .HasForeignKey("Ticket_PadreId");

                    b.HasOne("ServicesDeskUCABWS.Entities.Tipo_Ticket", "Tipo_Ticket")
                        .WithMany()
                        .HasForeignKey("Tipo_TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento_Destino");

                    b.Navigation("Emisor");

                    b.Navigation("Estado");

                    b.Navigation("Familia_Ticket");

                    b.Navigation("Prioridad");

                    b.Navigation("Responsable");

                    b.Navigation("Ticket_Padre");

                    b.Navigation("Tipo_Ticket");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Votos_Ticket", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Empleado", "Empleado")
                        .WithMany("Votos_Ticket")
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("ServicesDeskUCABWS.Entities.Ticket", "Ticket")
                        .WithMany("Votos_Ticket")
                        .HasForeignKey("TicketId");

                    b.Navigation("Empleado");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Empleado", b =>
                {
                    b.HasOne("ServicesDeskUCABWS.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("Cargoid");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Cargo", b =>
                {
                    b.Navigation("Flujo_Aprobacion");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Departamento", b =>
                {
                    b.Navigation("Tipo_Tickets");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Estado", b =>
                {
                    b.Navigation("Bitacora_Tickets");

                    b.Navigation("ListaTickets");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Etiqueta", b =>
                {
                    b.Navigation("etiquetaTipoEstado");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Familia_Ticket", b =>
                {
                    b.Navigation("Lista_Ticket");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Grupo", b =>
                {
                    b.Navigation("departamentos");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Ticket", b =>
                {
                    b.Navigation("Bitacora_Tickets");

                    b.Navigation("Votos_Ticket");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Tipo_Estado", b =>
                {
                    b.Navigation("etiquetaTipoEstado");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Tipo_Ticket", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("Flujo_Aprobacion");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Usuario", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ServicesDeskUCABWS.Entities.Empleado", b =>
                {
                    b.Navigation("Lista_Ticket");

                    b.Navigation("Tickets_Propios");

                    b.Navigation("Votos_Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
